### ISSUE TITLE
Couple of typos breaking your auth middleware

### ISSUE THREAD

**Issue by Roger-Heathcote** [fac20/week7-CHJM#43]
In authorise.js on line:19 'Bearer' should be 'Bearer ', otherwise it leaves a space at the start of the token string which causes the verify to fail.

And a few lines underneath that 'getUserbyID' should be 'getUserByID'. Your code currently ignores the error that is passed to it and makes the assumption jwt.verify has thrown and the token is therefore bad so this error was returning 401 Unauthorized. It's good to be specific when catching errors and check the error you have is the one you are expecting. If it's not the one you are after then it's good practice to re-throw it.

**Comment by jenndroid** [comment]
Fixed, thank you!
